[tool.poetry]
name = "elastic-ai-runtime-env5"
version = "0.1.0"
description = ""
authors = ["Department Embedded Systems - University Duisburg Essen"]
license = "MIT"
readme = "README.adoc"
packages = [{include = "python_utils"}]

[tool.poetry.dependencies]
python = "^3.10.0"
pyserial = "3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
