name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt-get install ninja-build
          mkdir ${{github.workspace}}/build_test

      - name: Configure CMake
        run: cmake -B cmake-build-debug/unit_test -D UNIT_TEST:BOOL=ON -D CMAKE_BUILD_TYPE=DEBUG -G Ninja .

      - name: Build
        run: cmake --build cmake-build-debug/unit_test -j 4

      - name: Run tests
        working-directory: ${{github.workspace}}/cmake-build-debug/unit_test/test/unit/
        env:
          FILES: unit-*
        run: for file in $FILES; do ./$file; done
